### ISSUE TITLE
Task not in release

### ISSUE THREAD

**Issue by maartenbeeckmans** [bertvv/ansible-role-vsftpd#13]
The task `Add extra (ACL) permissions` is specified in the file `/tasks/main.yml` on the master branch, but not yet in the latest release (v2.1.0)

```yml
- name: Add extra (ACL) permissions
  acl:
    name: "{{ item.folder }}"
    entity: "{{ item.entity }}"
    etype: "{{ item.etype }}"
    permissions: "{{ item.permissions }}"
    state: present
  with_items: "{{ vsftpd_extra_permissions }}"
  when: vsftpd_extra_permissions is defined
  tags: vsftpd
```
